services:
  sidecar-agent:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --config
      - /etc/firefly/sidecar-agent/sidecar-agent.minimal.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "15010:15010"
      - "15011:15011"
      - "15353:15353/udp"
      - "15353:15353/tcp"
    volumes:
      - ./deploy/agent/sidecar-agent.minimal.yaml:/etc/firefly/sidecar-agent/sidecar-agent.minimal.yaml:ro
    restart: unless-stopped
